# Generated by Django 2.0.7 on 2018-08-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.URLField(default='', verbose_name='视频连接'),
        ),
    ]
