# Generated by Django 2.0.7 on 2018-08-08 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20180808_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_bannes',
            field=models.BooleanField(default=False, verbose_name='是否首页推荐'),
        ),
    ]
