# Generated by Django 2.0.7 on 2018-08-03 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverifyrecord',
            name='exp_time',
            field=models.IntegerField(default=1, verbose_name='有效时间（天）'),
        ),
    ]
