# Generated by Django 2.0.7 on 2018-08-03 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_emailverifyrecord_exp_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverifyrecord',
            name='has_use',
            field=models.BooleanField(default=False, verbose_name='是否使用'),
        ),
    ]
