# Generated by Django 2.0.7 on 2018-08-03 10:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180803_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='exp_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='失效时间'),
        ),
    ]
